export const ITEM_TYPE = {
  ADD_FOOD: "ADD_FOOD",
  DECAREASE_FOOD: "DECAREASE_FOOD",
  REMOVE_FOOD: "REMOVE_FOOD",
  FOOD_FOODS: "FOOD_FOODS",
  USER_DATA: "USER_DATA",
  FOODS_DATA: "FOODS_DATA",
  PROMO_CODE: "PROMO_CODE",
};


